# Generated by Django 4.0.3 on 2022-03-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('energy_in_kcal', models.IntegerField()),
                ('fat', models.FloatField()),
                ('saturated_fat', models.FloatField()),
                ('carbohydrate', models.FloatField()),
                ('sugars', models.FloatField()),
                ('fibre', models.FloatField()),
                ('protein', models.FloatField()),
                ('salt', models.FloatField()),
            ],
        ),
    ]
